databases:
  - name: ironrent-db
    plan: free
    databaseName: ironrent
    user: ironrent

services:
  - type: web
    name: iron-rent
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ironrent-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: NODE_ENV
        value: production
    disk:
      name: uploads
      mountPath: /app/public/uploads
      sizeGB: 1
